Milestone 5
Tresor11/BookStore pull request #6
Opened 2020-05-21 21:12 UTC by Tresor11

On this branch, we added some styles to the app

2020-05-22 13:06 UTC, bolah2009 requested changes
Awesome job team!!! 👏🏾👏🏾👏🏾

The design looks good to me. However, can you please fix the issues listed below:
- Add working a  live link to the readme (see comments below).
- Remove unnecessary disabled ESLint rules (see https://github.com/Tresor11/BookStore/pull/3#pullrequestreview-416026269 for more details).
Examples are as follows:
   - https://github.com/Tresor11/BookStore/blob/fc01b3ff33a80f21f238eac1e3d052c3f1e653c3/src/containers/BooksForm.js#L1 
   - https://github.com/Tresor11/BookStore/blob/fc01b3ff33a80f21f238eac1e3d052c3f1e653c3/src/components/Book.js#L1
   - https://github.com/Tresor11/BookStore/blob/fc01b3ff33a80f21f238eac1e3d052c3f1e653c3/src/actions/index.js#L1
   - https://github.com/Tresor11/BookStore/blob/fc01b3ff33a80f21f238eac1e3d052c3f1e653c3/src/index.js#L1
   - https://github.com/Tresor11/BookStore/blob/fc01b3ff33a80f21f238eac1e3d052c3f1e653c3/src/serviceWorker.js#L1 You could delete this file since you not using it.

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-22 13:06 UTC, bolah2009 commented on README.md
> +[Live Demo Link](https://book-store-t.herokuapp.com/)
The live link seems to be showing an empty, page. Let's fix this.

https://book-store-t.herokuapp.com/

![image](https://user-images.githubusercontent.com/36057474/82670652-734f5480-9c35-11ea-8063-8f5e26ead4dc.png)

2020-05-22 13:06 UTC, bolah2009 commented on src/containers/BooksForm.js
>          </form>
[Optional]

Why not use the `onSubmit` on the `form` element instead, this way you get the native HTML5 form validation by default when you add the `required` attribute to each `input/select` element? 🤔 

See demo below where an empty book is added to the store, I don't think this should be the expected behaviour of the app.

![record1](https://user-images.githubusercontent.com/36057474/82669501-78130900-9c33-11ea-99cc-ee64f679c076.gif)

2020-05-26 01:59 UTC, fatymahmed approved these changes
## Hi @Tresor11 @Datagirlcmr 
 Great job making the required changes 🎉🎉
## ✔️ Approved!

2020-05-26 05:16 UTC, merged